### ISSUE TITLE
第一步生成wrap

### ISSUE THREAD

**Issue by scriptboy1990** [thenetcircle/faiss4j#1]

**Comment by scriptboy1990** [comment]
你好，请问下，我第一步生成wrap cpp文件成功了，第二步生成so的时候，会报大量类似于
swigfaiss_wrap.cxx:30308:21: error: expected primary-expression before ‘)’ token
   argp2 = *(idx_t **)&jarg2;
这种错误，请问是哪里的问题。

**Comment by cfcodefans** [comment]
没有遇到这种错误, 文档已经更新, 请对比环境差异.
